-- 002_seed.sql

-- Товары
INSERT INTO products (sku, name, type, price, currency, image, stock) VALUES
('STEAM-TOPUP-500', 'Пополнение Steam 500 ₽', 'topup', 500, 'RUB', 'assets/steam.png', 0),
('STEAM-TOPUP-1000', 'Пополнение Steam 1000 ₽', 'topup', 1000, 'RUB', 'assets/steam.png', 0),
('STEAM-TOPUP-2500', 'Пополнение Steam 2500 ₽', 'topup', 2500, 'RUB', 'assets/steam.png', 0),
('KEY-CS2-PRIME', 'CS2 Prime Status ключ', 'key', 1290, 'RUB', 'assets/cs2.png', 0),
('KEY-GTA5', 'GTA V ключ активации', 'key', 1990, 'RUB', 'assets/gta5.png', 0),
('KEY-EFT', 'Escape from Tarkov ключ', 'key', 3490, 'RUB', 'assets/eft.png', 0),
('SUB-DISCORD-1M', 'Discord Nitro 1 месяц', 'subscription', 399, 'RUB', 'assets/discord.png', 0),
('SUB-YT-3M', 'YouTube Premium 3 месяца', 'subscription', 1490, 'RUB', 'assets/youtube.png', 0),
('SUB-SPOTIFY-1M', 'Spotify Premium 1 месяц', 'subscription', 299, 'RUB', 'assets/spotify.png', 0),
('GIFT-PSN-1000', 'PlayStation Store карта 1000 ₽', 'giftcard', 1000, 'RUB', 'assets/psn.png', 0),
('GIFT-XBOX-1500', 'Xbox Gift Card 1500 ₽', 'giftcard', 1500, 'RUB', 'assets/xbox.png', 0),
('GIFT-ROBLOX-800', 'Roblox 800 Robux', 'giftcard', 890, 'RUB', 'assets/roblox.png', 0);

-- Пул ключей для KEY-товаров
INSERT INTO keys_pool (code, sku, status) VALUES
('LFXC-TNCS-BPCD', 'KEY-CS2-PRIME', 'available'),
('P3EI-W8UO-9B4K', 'KEY-CS2-PRIME', 'available'),
('FEL3-GUXN-TCCH', 'KEY-CS2-PRIME', 'available'),
('YPLV-QK2Z-IUS5', 'KEY-CS2-PRIME', 'available'),
('0K9E-P1FR-BY1U', 'KEY-CS2-PRIME', 'available'),
('5LZV-UQ48-RXCZ', 'KEY-CS2-PRIME', 'available'),
('X93K-NYAQ-GEC1', 'KEY-CS2-PRIME', 'available'),
('EIO5-CQT5-35KO', 'KEY-CS2-PRIME', 'available'),
('M58F-GIIR-VJAP', 'KEY-CS2-PRIME', 'available'),
('NU8Y-SWYB-6252', 'KEY-CS2-PRIME', 'available'),
('OODW-CCHF-MBAF', 'KEY-CS2-PRIME', 'available'),
('DNA5-WFJM-NE49', 'KEY-CS2-PRIME', 'available'),
('QRDD-MJ3F-A8TF', 'KEY-CS2-PRIME', 'available'),
('TAT9-5ZJN-G1T2', 'KEY-CS2-PRIME', 'available'),
('LI39-4330-ISMB', 'KEY-CS2-PRIME', 'available'),
('BKJY-8Q79-8NHI', 'KEY-CS2-PRIME', 'available'),
('HHW6-4RX2-DX62', 'KEY-CS2-PRIME', 'available'),
('1RG2-L28O-O80G', 'KEY-CS2-PRIME', 'available'),
('EF63-F39X-MTEA', 'KEY-CS2-PRIME', 'available'),
('8XS7-P53H-JKIV', 'KEY-CS2-PRIME', 'available'),
('JPE6-MQV6-P7ST', 'KEY-GTA5', 'available'),
('SAPG-A2GR-0ULS', 'KEY-GTA5', 'available'),
('T2DU-IJ1S-U16P', 'KEY-GTA5', 'available'),
('WSSY-QTR7-Z57J', 'KEY-GTA5', 'available'),
('U74E-EPCI-CY26', 'KEY-GTA5', 'available'),
('FZXF-58H8-OR93', 'KEY-GTA5', 'available'),
('FPSM-HLZA-TPAL', 'KEY-GTA5', 'available'),
('WSC9-28DJ-B2JE', 'KEY-GTA5', 'available'),
('P63J-F7UZ-DCYP', 'KEY-GTA5', 'available'),
('C7W2-D4C5-QMT7', 'KEY-EFT', 'available'),
('JESI-DFBH-LK1K', 'KEY-EFT', 'available'),
('SGMA-JA0T-GR7D', 'KEY-EFT', 'available'),
('3PR4-OSY9-M3ZW', 'KEY-EFT', 'available'),
('OMBE-C0JF-D45Y', 'KEY-EFT', 'available'),
('KIKQ-FQJ8-9TI8', 'KEY-EFT', 'available'),
('LMAN-RSHS-AJDO', 'KEY-EFT', 'available'),
('BAKI-VT1X-Z5OL', 'KEY-EFT', 'available'),
('9F0X-B46W-03FS', 'KEY-EFT', 'available'),
('S423-V6YY-IBEM', 'KEY-EFT', 'available'),
('D4UW-WYRA-20ST', 'KEY-EFT', 'available'),
('XC0J-CJ0H-09RN', 'KEY-EFT', 'available'),
('RY1W-XCFJ-0KUA', 'KEY-EFT', 'available'),
('CJYY-YKSQ-QE6H', 'KEY-EFT', 'available'),
('97AQ-38QJ-H8HU', 'KEY-EFT', 'available'),
('FS8E-3S5Z-I6RA', 'KEY-EFT', 'available'),
('ARQK-FML4-A14E', 'KEY-EFT', 'available'),
('7Z6K-NO9V-MPJB', 'KEY-EFT', 'available'),
('D4K7-IJSG-N853', 'KEY-EFT', 'available'),
('W67T-ZB0Q-1XKB', 'KEY-EFT', 'available'),
('7EQM-K09J-XKUO', 'KEY-EFT', 'available');

-- Пересчитываем stock для key-товаров из пула
UPDATE products SET stock = (SELECT COUNT(*) FROM keys_pool WHERE keys_pool.sku = products.sku AND keys_pool.status = 'available') WHERE type = 'key';